### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by Sk8er22** [jangrewe/WiPho#1]
```
"pathPhotos"    : "/104NIKON/",
>
>                           ^
>
> SyntaxError: Unexpected token :
>
> at exports.runInThisContext (vm.js:73:16)
>
> at Module._compile (module.js:443:25)
>
> at Object.Module._extensions..js (module.js:478:10)
>
> at Module.load (module.js:355:32)
>
> at Function.Module._load (module.js:310:12)
>
> at Module.require (module.js:365:17)
>
> at require (module.js:384:17)
```

It's already solved thanks to you with: 

path: /Users/myuser/Downloads/ 

ps: where can i implement a curl upload via http when it's already download the photo?

**Comment by jangrewe** [comment]
Hi Pedros, as already discussed via email, the relative path for the downloaded photos was the issue.

Regarding a POST after downloading, you could use something like https://github.com/chriso/curlrequest and add a call to that before (or instead of) the code block from line 156-169 (which creates a preview of the photo).

**Comment by Sk8er22** [comment]
Yep! Thank you so much!

**Comment by Sk8er22** [comment]
last question the photos are already downloaded but i have this error:

[DSCN0130.JPG] Saved as /Users/myuser/Downloads//DSCN0130.JPG
[DSCN0129.JPG] Downloading from http://192.168.1.19/sd/DCIM/104NIKON/DSCN0129.JPG
Photo resize error: Error: spawn gm ENOENT

i cannot see them in the web.

Thanks!

**Comment by jangrewe** [comment]
Ah, you need to have 'graphicsmagick' installed: http://www.graphicsmagick.org/
I'll need to add that to the README...

**Comment by Sk8er22** [comment]
DSCN0115.JPG] Saved as /Users/pedroarmandomanfredi/Downloads//DSCN0115.JPG
[DSCN0114.JPG] Downloading from http://192.168.1.19/sd/DCIM/104NIKON/DSCN0114.JPG
Photo resize error: Error: Command failed: gm convert: Unable to open file (./public/previews/DSCN0116.JPG) [No such file or directory].

another one u.u srsly THANKS xd i guess than it's searching in another directory... or it's not created the preview?

**Comment by Sk8er22** [comment]
Nothing! with real time pics works the preview :D thanks! done
